import Head from "next/head";
import Image from "next/image";
// import Link from "next/link";
// import shapeImage from "../public/images/shape/shape-1.svg";
// import shapeImage2 from "../public/images/shape/shape-2.svg";
// import shapeImage3 from "../public/images/shape/shape-3.svg";
// import shapeImage4 from "../public/images/shape/shape-4.svg";
import headerImage from "../public/images/header-image.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>TwitSoft</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />

        {/* <link rel="stylesheet" href="assets/css/animate.css" />

        <link rel="stylesheet" href="assets/css/tiny-slider.css" />

        <link rel="stylesheet" href="assets/fonts/lineicons/font-css/LineIcons.css" />

        <link rel="stylesheet" href="assets/css/tailwindcss.css" /> */}
      </Head>

      <div>
        {/* HEADER PART START */}

        <section className="header_area pt-32 pb-20">
          <div className="container">
            <div className="flex flex-row">
              <div className="w-full lg:w-1/2">
                <div className="header_hero_content pt-150 lg:pt-0">
                  <h2 className="hero_title text-2xl sm:text-4xl md:text-5xl lg:text-4xl xl:text-5xl font-extrabold">
                    We build iconic websites <br />
                    that people love
                  </h2>
                  <p className="mt-8 lg:mr-8">
                    Our dedicated IT teams will give you the power of next generation software
                    development solutions to help your business stand out.
                  </p>
                  <div className="hero_btn mt-10">
                    <a className="main-btn" href="#0">
                      Get Started
                    </a>
                  </div>
                </div>
              </div>
              <div className="header_shape hidden lg:block">
                <div className="header_image flex items-center">
                  <div className="image 2xl:pl-25">
                    <Image src={headerImage} alt="image image" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
}
