import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import headerImage from "../public/images/header-image.svg";
import aboutImage from "../public/images/about.svg";
import serviceImageWeb from "../public/images/m.jpg";
import serviceImageSoft from "../public/images/s.png";
import serviceImageApp from "../public/images/w.png";
import projectPos from "../public/images/pos.jpg";
import projectBlog from "../public/images/blogs.jpg";
import projectEcomm from "../public/images/ecom.png";
import projectSch from "../public/images/school.jpg";
import techImg from "../public/images/tech/program11.jpg";
import techImg1 from "../public/images/tech/program14.png";
import techImg2 from "../public/images/tech/program3.jpg";
import techImg3 from "../public/images/tech/program10.jpg";
import techImg4 from "../public/images/tech/program7.jpg";
import techImg5 from "../public/images/tech/vue.png";
import techImg6 from "../public/images/tech/program15.png";
import techImg7 from "../public/images/tech/program17.png";
import techImg8 from "../public/images/tech/program16.jpg";
import techImg9 from "../public/images/tech/next.svg";
import techImg10 from "../public/images/tech/tailwind.webp";
import techImg11 from "../public/images/tech/program4.png";
import teamImg1 from "../public/images/team/team1.jpg";
import teamImg2 from "../public/images/team/team2.jpg";
import teamImg3 from "../public/images/team/team3.jpg";
import teamImg4 from "../public/images/team/team4.jpg";
import teamImg5 from "../public/images/team/team5.webp";
import contactImage from "../public/images/contact.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>TwitSoft</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {/*--------- HEADER PART START------------ */}

        <section className="header_area pt-60 pb-20">
          <div className="container">
            <div className="flex flex-row">
              <div className="w-full lg:w-1/2">
                <div className="header_hero_content pt-150 lg:pt-0">
                  <div className="wrapper">
                    <div className="static-txt text-3xl sm:text-4xl md:text-5xl lg:text-4xl xl:text-4xl font-extrabold">
                      We build
                    </div>
                    <ul className="dynamic-txts text-3xl sm:text-4xl md:text-5xl lg:text-4xl xl:text-4xl font-extrabold">
                      <li>
                        <span>SaaS with pleasure</span>
                      </li>
                      <li>
                        <span>iconic websites</span>
                      </li>
                      <li>
                        <span>iOS & android apps</span>
                      </li>
                      <li>
                        <span>Software development </span>
                      </li>
                    </ul>
                  </div>
                  <p className="mt-8 lg:mr-8">
                    Our dedicated IT teams will give you the power of next generation software
                    development solutions to help your business stand out.
                  </p>
                  <div className="hero_btn mt-10">
                    <a className="main-btn" href="#0">
                      Get Started
                    </a>
                  </div>
                </div>
              </div>
              <div className="header_shape hidden lg:block">
                <div className="header_image flex items-center">
                  <div className="image 2xl:pl-25">
                    <Image src={headerImage} alt="image image" />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/*------------------------- HEADER PART END------------ */}

        {/*------------------------- ABOUT PART START------------ */}
        <section className="about_area pt-28 pb-40" id="about">
          <div className="container">
            <div className="row flex justify-center">
              <div className="w-full lg:w-1/2">
                <div className="section_title text-center pb-6">
                  <h5 className="text-red-500 text-2xl font-semibold">About</h5>
                  <h4 className="text-4xl font-bold mt-3">Work Process</h4>
                </div>
              </div>
            </div>
            <div className="grid grid-cols-3 gap-4 justify-center">
              <div className="w-full border-dotted border-2 animate-border inline-block bg-white from-pink-500 via-red-500 to-yellow-500 bg-[length:400%_400%] p-0.5 hover:bg-gradient-to-r border-slate-300 rounded-md pb-10">
                <div className="single_about text-center mt-8 mx-3">
                  <div className="services_icon flex justify-center">
                    <div className="parent_img">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="94"
                        height="92"
                        viewBox="0 0 94 92"
                      >
                        <path
                          id="Polygon_12"
                          data-name="Polygon 12"
                          d="M42.212,2.315a11,11,0,0,1,9.576,0l28.138,13.6a11,11,0,0,1,5.938,7.465L92.83,54.018A11,11,0,0,1,90.717,63.3L71.22,87.842A11,11,0,0,1,62.607,92H31.393a11,11,0,0,1-8.613-4.158L3.283,63.3A11,11,0,0,1,1.17,54.018L8.136,23.383a11,11,0,0,1,5.938-7.465Z"
                        />
                      </svg>
                    </div>
                    <div className="child_img">
                      <svg fill="#000000" viewBox="0 0 1920 1920" width="30" height="30">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            d="M1706.235 1807.059H350.941V112.94h903.53v451.765h451.764v1242.353Zm-338.823-1670.74 315.443 315.447h-315.443V136.32Zm402.182 242.487L1440.372 49.58C1408.296 17.62 1365.717 0 1320.542 0H238v1920h1581.175V498.635c0-45.176-17.618-87.755-49.58-119.83ZM576.823 1242.353h790.589v-112.94H576.823v112.94Zm0-451.765h903.53V677.647h-903.53v112.941Zm0 677.647h451.765v-112.941H576.823v112.941Zm0-451.764h677.648V903.53H576.823v112.941Zm0-451.765h451.765V451.765H576.823v112.941Z"
                            fill-rule="evenodd"
                          ></path>
                        </g>
                      </svg>
                    </div>
                  </div>
                  <div className="about_content mt-5">
                    <h3 className="about_title text-black font-semibold text-xl md:text-3xl">
                      Research
                    </h3>
                    <p className="mt-4">
                      Lorem ipsum dolor sit amet, consetetur sadi aliquyam erat, sed diam voluptua.
                      At vero eos accusam et justo duo dolores
                    </p>
                  </div>
                </div>
              </div>
              <div className="w-full border-dotted border-2 animate-border inline-block bg-white from-pink-500 via-red-500 to-yellow-500 bg-[length:400%_400%] p-0.5 hover:bg-gradient-to-r border-slate-300 rounded-md pb-10">
                <div className="single_about text-center mt-8 mx-3">
                  <div className="services_icon flex justify-center">
                    <div className="parent_img">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="94"
                        height="92"
                        viewBox="0 0 94 92"
                      >
                        <path
                          id="Polygon_12"
                          data-name="Polygon 12"
                          d="M42.212,2.315a11,11,0,0,1,9.576,0l28.138,13.6a11,11,0,0,1,5.938,7.465L92.83,54.018A11,11,0,0,1,90.717,63.3L71.22,87.842A11,11,0,0,1,62.607,92H31.393a11,11,0,0,1-8.613-4.158L3.283,63.3A11,11,0,0,1,1.17,54.018L8.136,23.383a11,11,0,0,1,5.938-7.465Z"
                        />
                      </svg>
                    </div>
                    <div className="child_img">
                      <svg fill="#000000" viewBox="0 0 1920 1920" width="30" height="30">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            d="M1706.235 1807.059H350.941V112.94h903.53v451.765h451.764v1242.353Zm-338.823-1670.74 315.443 315.447h-315.443V136.32Zm402.182 242.487L1440.372 49.58C1408.296 17.62 1365.717 0 1320.542 0H238v1920h1581.175V498.635c0-45.176-17.618-87.755-49.58-119.83ZM576.823 1242.353h790.589v-112.94H576.823v112.94Zm0-451.765h903.53V677.647h-903.53v112.941Zm0 677.647h451.765v-112.941H576.823v112.941Zm0-451.764h677.648V903.53H576.823v112.941Zm0-451.765h451.765V451.765H576.823v112.941Z"
                            fill-rule="evenodd"
                          ></path>
                        </g>
                      </svg>
                    </div>
                  </div>
                  <div className="about_content mt-5">
                    <h3 className="about_title text-black font-semibold text-xl md:text-3xl">
                      Prototype
                    </h3>
                    <p className="mt-4">
                      Lorem ipsum dolor sit amet, consetetur sadi aliquyam erat, sed diam voluptua.
                      At vero eos accusam et justo duo dolores
                    </p>
                  </div>
                </div>
              </div>
              <div className="w-full border-dotted border-2 animate-border inline-block bg-white from-pink-500 via-red-500 to-yellow-500 bg-[length:400%_400%] p-0.5 hover:bg-gradient-to-r border-slate-300 rounded-md pb-10">
                <div className="single_about text-center mt-8 mx-3">
                  <div className="services_icon flex justify-center">
                    <div className="parent_img">
                      <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="94"
                        height="92"
                        viewBox="0 0 94 92"
                      >
                        <path
                          id="Polygon_12"
                          data-name="Polygon 12"
                          d="M42.212,2.315a11,11,0,0,1,9.576,0l28.138,13.6a11,11,0,0,1,5.938,7.465L92.83,54.018A11,11,0,0,1,90.717,63.3L71.22,87.842A11,11,0,0,1,62.607,92H31.393a11,11,0,0,1-8.613-4.158L3.283,63.3A11,11,0,0,1,1.17,54.018L8.136,23.383a11,11,0,0,1,5.938-7.465Z"
                        />
                      </svg>
                    </div>
                    <div className="child_img">
                      <svg fill="#000000" viewBox="0 0 1920 1920" width="30" height="30">
                        <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
                        <g
                          id="SVGRepo_tracerCarrier"
                          stroke-linecap="round"
                          stroke-linejoin="round"
                        ></g>
                        <g id="SVGRepo_iconCarrier">
                          <path
                            d="M1706.235 1807.059H350.941V112.94h903.53v451.765h451.764v1242.353Zm-338.823-1670.74 315.443 315.447h-315.443V136.32Zm402.182 242.487L1440.372 49.58C1408.296 17.62 1365.717 0 1320.542 0H238v1920h1581.175V498.635c0-45.176-17.618-87.755-49.58-119.83ZM576.823 1242.353h790.589v-112.94H576.823v112.94Zm0-451.765h903.53V677.647h-903.53v112.941Zm0 677.647h451.765v-112.941H576.823v112.941Zm0-451.764h677.648V903.53H576.823v112.941Zm0-451.765h451.765V451.765H576.823v112.941Z"
                            fill-rule="evenodd"
                          ></path>
                        </g>
                      </svg>
                    </div>
                  </div>
                  <div className="about_content mt-5">
                    <h3 className="about_title text-black font-semibold text-xl md:text-3xl">
                      Build
                    </h3>
                    <p className="mt-4">
                      Lorem ipsum dolor sit amet, consetetur sadi aliquyam erat, sed diam voluptua.
                      At vero eos accusam et justo duo dolores
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <section id="why" className="about_area pt-120 relative pb-20">
          <div className="container">
            <div className="flex flex-row gap-x-6">
              <div className="image lg:pr-13">
                <Image src={aboutImage} alt="about" width={1000} height={900} />
              </div>

              <div className="">
                <div className="w-full">
                  <div className="about_content">
                    <div className="section_title pb-9">
                      <h5 className="text-red-500 text-2xl font-semibold">Why Choose Us</h5>
                      <h4 className="text-3xl font-bold mt-4">Your Goal is Our Achievement</h4>
                    </div>
                    <p>
                      In <span className="text-emerald-500">TwiteSoft</span> we follow a straight,
                      relaxing and transparent work life that uses an agile approach and not the
                      "old hierarchies". We want to break down the silos, share all we can and
                      empower all of us to be the best we can be. There is a word for this
                      organisation method, and it is Holacracy.
                    </p>
                    <div className="text-xl font-semibold mt-6">
                      <h4>We Like:</h4>
                    </div>
                    <ul className="about_list">
                      <li className="flex mt-5">
                        <div className="about_check">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            class="w-6 h-6"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M4.5 12.75l6 6 9-13.5"
                            />
                          </svg>
                        </div>
                        <div className="about_list_content pl-5 pr-2">
                          <p>Open team based work life</p>
                        </div>
                      </li>
                      <li className="flex mt-5">
                        <div className="about_check">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            class="w-6 h-6"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M4.5 12.75l6 6 9-13.5"
                            />
                          </svg>
                        </div>
                        <div className="about_list_content pl-5 pr-2">
                          <p>Self-thinking agile teams</p>
                        </div>
                      </li>
                      <li className="flex mt-5">
                        <div className="about_check">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            fill="none"
                            viewBox="0 0 24 24"
                            stroke-width="1.5"
                            stroke="currentColor"
                            class="w-6 h-6"
                          >
                            <path
                              stroke-linecap="round"
                              stroke-linejoin="round"
                              d="M4.5 12.75l6 6 9-13.5"
                            />
                          </svg>
                        </div>
                        <div className="about_list_content pl-5 pr-2">
                          <p>A trust based open mindset</p>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/*-------------------------- ABOUT PART END------------ */}

        {/*-------------------------- SERVICES PART END------------ */}
        <section className="services_area pt-28 pb-16" id="services">
          <div className="container">
            <div className="row flex justify-center">
              <div className="w-full lg:w-1/2">
                <div className="section_title text-center pb-6">
                  <h5 className="text-red-500 text-2xl font-semibold">What We Do</h5>
                  <h4 className="text-4xl font-bold mt-3">Our Services</h4>
                </div>
              </div>
            </div>
            <div className="grid grid-cols-3 gap-4 justify-center">
              <div className="w-full  pb-10">
                <div className="single_service text-center mt-8 mx-3 shadow-lg p-2">
                  <div className="services_icon flex justify-center">
                    <Image src={serviceImageWeb} alt="services image" height={200} />
                  </div>
                  <div className="services_content mt-5">
                    <h3 className="services_title text-black font-semibold text-xl md:text-3xl hover:text-red-500">
                      <Link href="#"> Mobile App development</Link>
                    </h3>
                    <p className="text-justify mt-4">
                      With over a decade of experience, TwiteSoft Technology is able to prototype,
                      design, develop and integrate seamlessly mobile apps with your current
                      website. Our innovative designs make sure that the user experience of your app
                      is excellent.
                    </p>
                  </div>
                </div>
              </div>
              <div className="w-full pb-10">
                <div className="single_services text-center mt-8 mx-3 shadow-lg p-2">
                  <div className="services_icon flex justify-center">
                    <Image src={serviceImageApp} alt="services image" height={200} />
                  </div>
                  <div className="services_content mt-5">
                    <h3 className="services_title text-black font-semibold text-xl md:text-3xl hover:text-red-500">
                      <Link href="#"> Website development</Link>
                    </h3>
                    <p className="text-justify mt-4">
                      Bespoke website design and development is one of our core skills to help your
                      business succeed online. We specialize in professional web solutions from
                      simple one page to complex, database driven, and dynamic websites with a CMS.
                    </p>
                  </div>
                </div>
              </div>
              <div className="w-full pb-10">
                <div className="single_services text-center mt-8 mx-3 shadow-lg p-2">
                  <div className="services_icon flex justify-center">
                    <Image src={serviceImageSoft} alt="services image" height={200} />
                  </div>
                  <div className="services_content mt-5">
                    <h3 className="services_title text-black font-semibold text-xl md:text-3xl hover:text-red-500">
                      <Link href="#">Software development</Link>
                    </h3>
                    <p className="text-justify mt-4">
                      Our professional software developers build software systems and dynamic
                      web-based applications to satisfy even the most complicated business needs. We
                      can find solutions to even the most complex and demanding issues on time and
                      on budget.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/*-------------------------- SERVICES PART END------------ */}

        {/*-------------------------- PROJECTS PART START------------ */}
        <section className="project_area pt-28 pb-28 bg-gray-50" id="project">
          <div className="container">
            <div className="row flex justify-center">
              <div className="w-full lg:w-1/2">
                <div className="section_title text-center pb-6">
                  <h5 className="text-red-500 text-2xl font-semibold">We love development</h5>
                  <h4 className="text-4xl font-bold mt-3">Some of Our Recent Works</h4>
                </div>
              </div>
            </div>
            <div className="grid grid-cols-3 gap-2 justify-center">
              <div className="w-full">
                <div className="single_service text-center mt-8 mx-3 shadow-lg p-2">
                  <div className="services_icon flex justify-center">
                    <Image src={projectSch} alt="services image" height={200} />
                  </div>
                  <div className="services_content mt-5">
                    <h3 className="services_title text-black font-semibold text-xl md:text-xl hover:text-red-500">
                      <Link href="#"> SCHOOL MANAGEMENT SYSTEM</Link>
                    </h3>
                    <p className="text-justify mt-4">PHP, Laravel , MySQL</p>
                  </div>
                </div>
              </div>
              <div className="w-full">
                <div className="single_services text-center mt-8 mx-3 shadow-lg p-2">
                  <div className="services_icon flex justify-center">
                    <Image src={projectPos} alt="services image" height={200} />
                  </div>
                  <div className="services_content mt-5 pb-3">
                    <h3 className="services_title text-black font-semibold text-xl md:text-xl hover:text-red-500">
                      <Link href="#"> POS SYSTEM</Link>
                    </h3>
                    <p className="text-justify mt-4">Vue,PHP, Laravel , MySQL</p>
                  </div>
                </div>
              </div>
              <div className="w-full">
                <div className="single_services text-center mt-8 mx-3 shadow-lg p-2">
                  <div className="services_icon flex justify-center">
                    <Image src={projectBlog} alt="services image" height={200} />
                  </div>
                  <div className="services_content mt-5">
                    <h3 className="services_title text-black font-semibold text-xl md:text-xl hover:text-red-500">
                      <Link href="#">BLOG SYSTEM</Link>
                    </h3>
                    <p className="text-justify mt-4">PHP, Laravel , MySQL</p>
                  </div>
                </div>
              </div>
              <div className="w-full ">
                <div className="single_services text-center mt-8 mx-3 shadow-lg p-2">
                  <div className="services_icon flex justify-center">
                    <Image src={projectEcomm} alt="services image" height={200} />
                  </div>
                  <div className="services_content mt-5">
                    <h3 className="services_title text-black font-semibold text-xl md:text-xl hover:text-red-500">
                      <Link href="#">E-COMMERCE WEBSITE</Link>
                    </h3>
                    <p className="text-justify mt-4">PHP, Laravel , MySQL</p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        {/*-------------------------- PROJECTS PART END------------ */}

        {/*-------------------------- Technology PART Start------------ */}
        <section className="technology_area pb-40 bg-gray-50">
          <div className="container">
            <div className="row flex justify-center">
              <div className="w-full lg:w-1/2">
                <div className="section_title text-center pb-6">
                  <h5 className="text-red-500 text-2xl font-semibold">TECHNOLOGIES</h5>
                  <h4 className="text-xl font-bold mt-3">All The Technologies That We Use</h4>
                </div>
              </div>
            </div>

            <div className="grid grid-cols-4 gap-4">
              <div className="flex flex-col md:flex-row rounded-lg bg-white shadow-lg ">
                <Image
                  src={techImg}
                  alt="image"
                  className="rounded-full p-3"
                  width={70}
                  height={70}
                />

                <div className="flex flex-col justify-start p-2">
                  <h5 className="text-gray-900 text-xl font-semibold mb-2 hover:underline">
                    <Link href="#">Python </Link>
                  </h5>
                </div>
              </div>
              <div className="flex flex-col md:flex-row rounded-lg bg-white shadow-lg ">
                <Image
                  src={techImg1}
                  alt="image"
                  className="rounded-full p-3"
                  width={100}
                  height={100}
                />

                <div className="flex flex-col justify-start p-2">
                  <h5 className="text-gray-900 text-xl font-semibold mb-2 hover:underline">
                    <Link href="#">Laravel </Link>
                  </h5>
                </div>
              </div>
              <div className="flex flex-col md:flex-row rounded-lg bg-white shadow-lg ">
                <Image
                  src={techImg2}
                  alt="image"
                  className="rounded-full p-3"
                  width={100}
                  height={100}
                />

                <div className="flex flex-col justify-start p-2">
                  <h5 className="text-gray-900 text-xl font-semibold mb-2 hover:underline">
                    <Link href="#">JavaScript </Link>
                  </h5>
                </div>
              </div>
              <div className="flex flex-col md:flex-row rounded-lg bg-white shadow-lg ">
                <Image
                  src={techImg3}
                  alt="image"
                  className="rounded-full p-3"
                  width={100}
                  height={100}
                />

                <div className="flex flex-col justify-start p-2">
                  <h5 className="text-gray-900 text-xl font-semibold mb-2 hover:underline">
                    <Link href="#">PHP </Link>
                  </h5>
                </div>
              </div>
              <div className="flex flex-col md:flex-row rounded-lg bg-white shadow-lg ">
                <Image
                  src={techImg4}
                  alt="image"
                  className="rounded-full p-3"
                  width={100}
                  height={100}
                />

                <div className="flex flex-col justify-start p-2">
                  <h5 className="text-gray-900 text-xl font-semibold mb-2 hover:underline">
                    <Link href="#">React </Link>
                  </h5>
                </div>
              </div>
              <div className="flex flex-col md:flex-row rounded-lg bg-white shadow-lg ">
                <Image
                  src={techImg5}
                  alt="image"
                  className="rounded-full p-3"
                  width={100}
                  height={100}
                />

                <div className="flex flex-col justify-start p-2">
                  <h5 className="text-gray-900 text-xl font-semibold mb-2 hover:underline">
                    <Link href="#">Vue JS </Link>
                  </h5>
                </div>
              </div>
              <div className="flex flex-col md:flex-row rounded-lg bg-white shadow-lg ">
                <Image
                  src={techImg6}
                  alt="image"
                  className="rounded-full p-3"
                  width={100}
                  height={100}
                />

                <div className="flex flex-col justify-start p-2">
                  <h5 className="text-gray-900 text-xl font-semibold mb-2 hover:underline">
                    <Link href="#">Django </Link>
                  </h5>
                </div>
              </div>
              <div className="flex flex-col md:flex-row rounded-lg bg-white shadow-lg ">
                <Image
                  src={techImg7}
                  alt="image"
                  className="rounded-full p-3"
                  width={100}
                  height={100}
                />

                <div className="flex flex-col justify-start p-2">
                  <h5 className="text-gray-900 text-xl font-semibold mb-2 hover:underline">
                    <Link href="#">MongoDB </Link>
                  </h5>
                </div>
              </div>
              <div className="flex flex-col md:flex-row rounded-lg bg-white shadow-lg ">
                <Image
                  src={techImg8}
                  alt="image"
                  className="rounded-full p-3"
                  width={100}
                  height={100}
                />

                <div className="flex flex-col justify-start p-2">
                  <h5 className="text-gray-900 text-xl font-semibold mb-2 hover:underline">
                    <Link href="#">MySQL </Link>
                  </h5>
                </div>
              </div>
              <div className="flex flex-col md:flex-row rounded-lg bg-white shadow-lg ">
                <Image
                  src={techImg9}
                  alt="image"
                  className="rounded-full p-3"
                  width={100}
                  height={100}
                />

                <div className="flex flex-col justify-start p-2">
                  <h5 className="text-gray-900 text-xl font-semibold mb-2 hover:underline">
                    <Link href="#">Next JS </Link>
                  </h5>
                </div>
              </div>
              <div className="flex flex-col md:flex-row rounded-lg bg-white shadow-lg ">
                <Image
                  src={techImg10}
                  alt="image"
                  className="rounded-full p-3"
                  width={100}
                  height={100}
                />

                <div className="flex flex-col justify-start p-2">
                  <h5 className="text-gray-900 text-xl font-semibold mb-2 hover:underline">
                    <Link href="#">Tailwind CSS </Link>
                  </h5>
                </div>
              </div>
              <div className="flex flex-col md:flex-row rounded-lg bg-white shadow-lg ">
                <Image
                  src={techImg11}
                  alt="image"
                  className="rounded-full p-3"
                  width={100}
                  height={100}
                />

                <div className="flex flex-col justify-start p-2">
                  <h5 className="text-gray-900 text-xl font-semibold mb-2 hover:underline">
                    <Link href="#">Bootstrap </Link>
                  </h5>
                </div>
              </div>
            </div>
            <div className="row flex justify-center mt-8">
              <Link
                href=""
                type="button"
                className="inline-block px-6 py-2.5 bg-blue-400 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-500 hover:shadow-lg focus:bg-blue-500 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-600 active:shadow-lg transition duration-150 ease-in-out"
              >
                Show More
              </Link>
            </div>
          </div>
        </section>
        {/*-------------------------- Technology PART END------------ */}

        {/*-------------------------- TEAM PART START------------ */}
        <section className="team_area pt-28 pb-16" id="team">
          <div className="container">
            <div className="row flex justify-center">
              <div className="w-full lg:w-1/2">
                <div className="section_title text-center pb-6">
                  <h4 className="text-4xl font-bold mt-3 ">Meet Our Team Members</h4>
                </div>
              </div>
            </div>
            <div className="grid grid-cols-4 gap-1 justify-center">
              <div className="w-full  pb-10">
                <div className="single_team text-center mt-8 mx-3 shadow-lg  p-2">
                  <div className="team_icon flex justify-center">
                    <Image src={teamImg1} alt="team image" className="rounded" height={200} />
                  </div>
                  <div className="team_content mt-5">
                    <h3 className="team_title text-black font-semibold text-xl md:text-xl">
                      Al-Mamun Sarkar
                    </h3>
                    <p className="text-center mt-4">Co-founder and CEO</p>
                  </div>
                  <div className="team_social pt-4 mx-3 text-center">
                    <ul className="social flex justify-center sm:justify-start">
                      <li className="mr-3">
                        <Link href=""></Link>
                      </li>
                      <li className="mr-3">
                        <Link href="#">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm3 8h-1.35c-.538 0-.65.221-.65.778v1.222h2l-.209 2h-1.791v7h-3v-7h-2v-2h2v-2.308c0-1.769.931-2.692 3.029-2.692h1.971v3z" />
                          </svg>
                        </Link>
                      </li>
                      <li className="mr-3">
                        <Link href="#">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z" />
                          </svg>
                        </Link>
                      </li>
                      <li className="mr-3 text-white">
                        <Link href="">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                          </svg>
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="w-full pb-10">
                <div className="single_team text-center mt-8 mx-3 shadow-lg p-2">
                  <div className="services_icon flex justify-center">
                    <Image src={teamImg2} alt="team image" className="rounded" height={200} />
                  </div>
                  <div className="team_content mt-5">
                    <h3 className="team_title text-black font-semibold text-xl md:text-x">
                      Abdur Rahman
                    </h3>
                    <p className="text-center mt-4">Co-Founder and Project manager</p>
                  </div>
                  <div className="team_social pt-4 mx-3 text-center">
                    <ul className="social flex justify-center sm:justify-start">
                      <li className="mr-3">
                        <Link href=""></Link>
                      </li>
                      <li className="mr-3">
                        <Link href="#">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm3 8h-1.35c-.538 0-.65.221-.65.778v1.222h2l-.209 2h-1.791v7h-3v-7h-2v-2h2v-2.308c0-1.769.931-2.692 3.029-2.692h1.971v3z" />
                          </svg>
                        </Link>
                      </li>
                      <li className="mr-3">
                        <Link href="#">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z" />
                          </svg>
                        </Link>
                      </li>
                      <li className="mr-3 text-white">
                        <Link href="">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                          </svg>
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="w-full pb-10">
                <div className="single_team text-center mt-8 mx-3 shadow-lg p-2">
                  <div className="team_icon flex justify-center">
                    <Image src={teamImg3} alt="team image" className="rounded" height={200} />
                  </div>
                  <div className="team_content mt-5">
                    <h3 className="team_title text-black font-semibold text-xl md:text-xl ">
                      Md. Tipu Sultan
                    </h3>
                    <p className="text-center mt-4">Co-Founder and Tech Lead</p>
                  </div>
                  <div className="team_social pt-4 mx-3 text-center">
                    <ul className="social flex justify-center sm:justify-start">
                      <li className="mr-3">
                        <Link href=""></Link>
                      </li>
                      <li className="mr-3">
                        <Link href="#">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm3 8h-1.35c-.538 0-.65.221-.65.778v1.222h2l-.209 2h-1.791v7h-3v-7h-2v-2h2v-2.308c0-1.769.931-2.692 3.029-2.692h1.971v3z" />
                          </svg>
                        </Link>
                      </li>
                      <li className="mr-3">
                        <Link href="#">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z" />
                          </svg>
                        </Link>
                      </li>
                      <li className="mr-3 text-white">
                        <Link href="">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                          </svg>
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="w-full pb-10">
                <div className="single_team text-center mt-8 mx-3 shadow-lg p-2">
                  <div className="team_icon flex justify-center">
                    <Image src={teamImg4} alt="team image" className="rounded" height={200} />
                  </div>
                  <div className="team_content mt-5">
                    <h3 className="team_title text-black font-semibold text-xl md:text-x">
                      Md. Rajib Mia Rahid
                    </h3>
                    <p className="text-center mt-4">Web Application developer</p>
                  </div>
                  <div className="team_social pt-4 mx-3 text-center">
                    <ul className="social flex justify-center sm:justify-start">
                      <li className="mr-3">
                        <Link href=""></Link>
                      </li>
                      <li className="mr-3">
                        <Link href="#">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm3 8h-1.35c-.538 0-.65.221-.65.778v1.222h2l-.209 2h-1.791v7h-3v-7h-2v-2h2v-2.308c0-1.769.931-2.692 3.029-2.692h1.971v3z" />
                          </svg>
                        </Link>
                      </li>
                      <li className="mr-3">
                        <Link href="#">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z" />
                          </svg>
                        </Link>
                      </li>
                      <li className="mr-3 text-white">
                        <Link href="">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                          </svg>
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
              <div className="w-full pb-10">
                <div className="single_team text-center mt-8 mx-3 shadow-lg p-2">
                  <div className="team_icon flex justify-center">
                    <Image src={teamImg5} alt="team image" className="rounded" height={200} />
                  </div>
                  <div className="team_content mt-5">
                    <h3 className="team_title text-black font-semibold text-xl md:text-xl">
                      Md. Alamin Islam
                    </h3>
                    <p className="text-center mt-4">Laravel developer</p>
                  </div>
                  <div className="team_social pt-4 mx-3 text-center">
                    <ul className="social flex justify-center sm:justify-start">
                      <li className="mr-3">
                        <Link href=""></Link>
                      </li>
                      <li className="mr-3">
                        <Link href="#">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M12 0c-6.627 0-12 5.373-12 12s5.373 12 12 12 12-5.373 12-12-5.373-12-12-12zm3 8h-1.35c-.538 0-.65.221-.65.778v1.222h2l-.209 2h-1.791v7h-3v-7h-2v-2h2v-2.308c0-1.769.931-2.692 3.029-2.692h1.971v3z" />
                          </svg>
                        </Link>
                      </li>
                      <li className="mr-3">
                        <Link href="#">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z" />
                          </svg>
                        </Link>
                      </li>
                      <li className="mr-3 text-white">
                        <Link href="">
                          <svg
                            xmlns="http://www.w3.org/2000/svg"
                            width="24"
                            height="24"
                            viewBox="0 0 24 24"
                          >
                            <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
                          </svg>
                        </Link>
                      </li>
                    </ul>
                  </div>
                </div>
              </div>
            </div>
            <div className="row flex justify-center mt-8">
              <Link
                href=""
                type="button"
                className="inline-block px-6 py-2.5 bg-blue-400 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-blue-500 hover:shadow-lg focus:bg-blue-500 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-blue-600 active:shadow-lg transition duration-150 ease-in-out"
              >
                Show More
              </Link>
            </div>
          </div>
        </section>
        {/*-------------------------- TEAM PART END------------ */}

        {/*-------------------------- CONTACT PART START------------ */}
        <section className="contact_area pt-20 bg-gray-50 pb-20">
          <div className="container">
            <div className="flex flex-row">
              <div className="contact hidden lg:block">
                <div className="header_image flex items-center">
                  <div className="image 2xl:pl-25">
                    <Image src={contactImage} alt="contact-image" width={700} />
                  </div>
                </div>
              </div>

              <div className="w-full lg:w-1/2">
                <div className="contact_wrapper">
                  <div className="section_title pb-4">
                    <h5 className="text-4xl font-bold">Contact</h5>
                    <h4 className="text-base font-semibold mt-3">Get In Touch</h4>
                  </div>

                  <div className="contact_form">
                    <form id="contact-form" action="#" method="POST">
                      <div className="row">
                        <div className="w-full ">
                          <div className=" mx-3">
                            <div className="single_form mt-8">
                              <input
                                name="name"
                                id="name"
                                type="text"
                                placeholder="Name"
                                className="w-full rounded-md py-4 px-6 border border-solid border-body-color"
                              />
                            </div>
                            <div className="single_form mt-8">
                              <input
                                name="email"
                                id="email"
                                type="email"
                                placeholder="Email"
                                className="w-full rounded-md py-4 px-6 border border-solid border-body-color"
                              />
                            </div>
                          </div>
                        </div>

                        <div className="w-full">
                          <div className="mx-3">
                            <div className="single_form mt-8">
                              <textarea
                                name="message"
                                id="message"
                                placeholder="Message"
                                rows="5"
                                className="w-full rounded-md py-4 px-6 border border-solid border-body-color resize-none"
                              ></textarea>
                            </div>
                          </div>
                        </div>
                        <p className="form-message mx-3"></p>
                        <div className="w-full">
                          <div className="mx-3">
                            <div className="single_form mt-8">
                              <button
                                type="button"
                                class="inline-block px-6 py-2.5 bg-red-600 text-white font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-red-700 hover:shadow-lg focus:bg-red-700 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-red-800 active:shadow-lg transition duration-150 ease-in-out"
                              >
                                Submit
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/*-------------------------- CONTACT PART END------------ */}
      </div>
    </>
  );
}
